### ISSUE TITLE
Choose cards to play

### ISSUE THREAD

**Issue by einarhaaland** [inf112-v20/weirdsixters#28]
Som spiller vil jeg velge kort for å kunne queue kort som skal spilles.

Krav:
Gitt at man velger 5 kort, så blir de gitt rekkefølge og får visual feedback.

Oppgaver:
1. Lag en metode Game.stageCard(Card) som blir kalt fra Game.keyDown
1. Bruk tastene 1-9 for å flytte kort fra hånden til robot.registers.
   - Hånden kan ha tomme plasser mellom kort, bare sett plassen til null etter kortet flyttes.
   - Legg til kort på enden av registers

**Comment by zargot** [comment]
Blocked by #76.
