### ISSUE TITLE
Make it so that the sprite rotates when the robot rotates

### ISSUE THREAD

**Issue by SanderBerge** [inf112-v20/weirdsixters#45]
Som spiller vil jeg at spriten skal rotere sammen med roboten slik at jeg vet hvor roboten vender. 

Denne oppgaven vil være fullført når spriten vender sammen med roboten.

**Comment by zargot** [comment]
Her kan det være en fordel at roboten har retning mot høyre i selve bilde, slik at zero rotation tilsvarer øst. Det er fordi `(new Vector2(1, 0)).angle() == 0`, altså en vektor mot høyre har rotasjon null, såvidt jeg vet. Dette er ihvertfall en vanlig konvensjon i andre rammeverk.
